name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出项目代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 使用 GitHub Secrets 中的 Docker Hub 凭证进行登录
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest .

      # 推送 Docker 镜像到 Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest

      # 使用 GitHub Secrets 中的 SSH 密钥通过 SSH 执行命令
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}   # 服务器 IP 或主机名
          username: ${{ secrets.SERVER_USER }}  # SSH 用户名
          key: ${{ secrets.SERVER_SECRET }}    # SSH 私钥
          port: ${{ secrets.SERVER_SSH_PORT }}  # SSH 端口，默认是22
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest
            cd /path/to/docker-compose-directory  # 替换为docker-compose所在的目录
            docker compose restart
